In [121]:
print("14 March 2026")

14 March 2026

In [122]:
import numpy as np 
import pandas as pd

In [123]:
# astype --> 1 data type ko dusre datatype me convert krna

In [124]:
df = pd.read_csv("placement.csv")
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

astype() #Type Conversion

In [125]:
# x = df.astype(int) #Type Conversion

In [126]:
df['cgpa'] = df['cgpa'].astype(int)

In [127]:
df

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

.add() --> TO incerement

In [128]:
df['cgpa'] = df['cgpa'].add(4)
df

p = df.count()
print("Count:",p)
print()

q =df.min()
print("Min:",q)
print()

r =df.max()
print("Max:",r)

l = df.describe()
print("All:",l)

Count: cgpa            100
resume_score    100
placed          100
dtype: int64

Min: cgpa            9.00
resume_score    4.95
placed          0.00
dtype: float64

Max: cgpa            13.00
resume_score     9.06
placed           1.00
dtype: float64
All:              cgpa  resume_score      placed
count  100.000000    100.000000  100.000000
mean    10.470000      6.930500    0.500000
std      1.201472      0.979608    0.502519
min      9.000000      4.950000    0.000000
25%      9.000000      6.190000    0.000000
50%     10.000000      7.055000    0.500000
75%     12.000000      7.640000    1.000000
max     13.000000      9.060000    1.000000

mean / median --> TO Find The Avg

In [129]:
a =df['cgpa'].mean()
print(a)
# df.mean()

10.47

In [130]:
b = df['cgpa'].median()
b

np.float64(10.0)

In [131]:
# df = pd.DataFrame({
#     "marks": [50, 60, 70, 80, 200]
# })

# print(df["marks"].mean()) #(50+60+70+80+200)/5
# print(df["marks"].median()) #Middle Value

In [132]:
g = df.filter(items=['cgpa','placed'])
g
# df[['cgpa','placed']] # Second Option ot filter rows

    cgpa  placed
0     12       1
1     10       0
2     12       1
3     10       1
4     11       1
..   ...     ...
95    10       0
96    12       1
97    10       0
98    12       1
99    10       0

[100 rows x 2 columns]

axis = 0 means Row Wist Operation

In [133]:
s =df.filter(items=[5,6],axis=0) #Row Wise Operation 
s

   cgpa  resume_score  placed
5    12          6.19       1
6     9          7.09       0

In [134]:
s = df.to_dict() # Save in dictonary 
# s

In [135]:
q = df.to_string() # Save in String 
# e = df.to_csv("Path_Location") #Save in Csv File

In [136]:
idx = df.columns  # it will Returns the columns name in a list 
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='str')

In [137]:
label = df.columns[0] # First Column Label(Index Column)
label

'cgpa'

In [138]:
p =df.columns.tolist() #List of Columns Label 
p

['cgpa', 'resume_score', 'placed']

In [139]:
q = df.columns.values #Arrary of Columns labels
q

<StringArray>
['cgpa', 'resume_score', 'placed']
Length: 3, dtype: str

dataframe.rename(columns = {'col1_name':'Updated_name'})

In [140]:
p = df.rename(columns={'cgpa':'updated_cgpa' , 'resume_score':'semester_marks'}) #Rename the columns name 
p

    updated_cgpa  semester_marks  placed
0             12            6.52       1
1             10            5.17       0
2             12            8.86       1
3             10            7.27       1
4             11            7.30       1
..           ...             ...     ...
95            10            6.38       0
96            12            7.76       1
97            10            7.78       0
98            12            5.63       1
99            10            6.61       0

[100 rows x 3 columns]

In [141]:
df['half'] = df['cgpa'].where(df['cgpa'] >7 , other=0)
df.head(10)
# where are used to check the condition is true or not and other fill the 0 if condition is false

   cgpa  resume_score  placed  half
0    12          6.52       1    12
1    10          5.17       0    10
2    12          8.86       1    12
3    10          7.27       1    10
4    11          7.30       1    11
5    12          6.19       1    12
6     9          7.09       0     9
7    10          6.29       0    10
8    10          6.71       0    10
9    11          7.12       1    11

In [142]:
d = pd.read_csv('tips.csv')
d.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [143]:
# row =11 ot 13
# columns = 3
# 2 columns name rename 
# new colummns Name =  Male Customers
# total_bill --> integers

In [144]:
a = d.filter(items=[11,12,13] , axis=0)
a

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4

In [145]:
r = d.rename(columns={'sex':'Male_customers' , 'day':'din'})
r

     total_bill   tip Male_customers smoker   din    time  size
0         16.99  1.01         Female     No   Sun  Dinner     2
1         10.34  1.66           Male     No   Sun  Dinner     3
2         21.01  3.50           Male     No   Sun  Dinner     3
3         23.68  3.31           Male     No   Sun  Dinner     2
4         24.59  3.61         Female     No   Sun  Dinner     4
..          ...   ...            ...    ...   ...     ...   ...
239       29.03  5.92           Male     No   Sat  Dinner     3
240       27.18  2.00         Female    Yes   Sat  Dinner     2
241       22.67  2.00           Male    Yes   Sat  Dinner     2
242       17.82  1.75           Male     No   Sat  Dinner     2
243       18.78  3.00         Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [146]:
d['male_customers'] = d['sex'].where(d['sex'] == 'Male' , other =0)

In [147]:
ll = d['total_bill'].astype(int)

In [148]:
d

     total_bill   tip     sex smoker   day    time  size male_customers
0         16.99  1.01  Female     No   Sun  Dinner     2              0
1         10.34  1.66    Male     No   Sun  Dinner     3           Male
2         21.01  3.50    Male     No   Sun  Dinner     3           Male
3         23.68  3.31    Male     No   Sun  Dinner     2           Male
4         24.59  3.61  Female     No   Sun  Dinner     4              0
..          ...   ...     ...    ...   ...     ...   ...            ...
239       29.03  5.92    Male     No   Sat  Dinner     3           Male
240       27.18  2.00  Female    Yes   Sat  Dinner     2              0
241       22.67  2.00    Male    Yes   Sat  Dinner     2           Male
242       17.82  1.75    Male     No   Sat  Dinner     2           Male
243       18.78  3.00  Female     No  Thur  Dinner     2              0

[244 rows x 8 columns]