In [1]:
print("Day3")

Day3

In [5]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\Python_Regex\\Pandas\\pandas\\placement.csv")
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [7]:
df.head() # By default 5

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [ ]:
df.describe() # Staticaly view of data

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [ ]:
df.info() # it will return's the overall details of the data (Data Type Information)

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [13]:
top_left_corner_df = df.iloc[:4,:3] # iloc[row_range ,columns_range]
top_left_corner_df

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [15]:
df.loc[1:3 , ['cgpa' , 'placed']] # loc[row_range , column_name]

   cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [ ]:
s = df.axes 
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='str')]

In [ ]:
p = df.dtypes # To Check The Data Types of the data in the files 
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [18]:
df['cgpa'].dtypes

dtype('float64')

In [20]:
b =df.empty ##it returns true if there any missing data in dataframe otherwise returns False
b

False

In [22]:
df.isnull().sum()  #  For Check Missing Values

cgpa            0
resume_score    0
placed          0
dtype: int64

In [23]:
df = df.dropna() # For Remove Missing Row

In [27]:
i = df.ndim # NUmber Of Axes (it is 2)
i

2

In [29]:
t =df.shape # shape = n(rows) , n(columns)
t

(100, 3)