In [215]:
print("All Pandas Code Here")

All Pandas Code Here

In [216]:
# !pip install pandas

In [217]:
import pandas as pd

In [218]:
print("Serise is a One Dimentional ")
print("-----------------------------")
data = [1,2,3,4,5,6,7]

df = pd.Series(data)
print("TYPE SERISE OF LIST DATA",type(df))

# usign Dictonary
dct = {
    "Name":[1,2,3,4,5,6],
    "Age":[18,19,20,21,22,23]
}

df1 = pd.Series(dct)
print("TYPE SERISE OF DICTONARY DATA ",type(df1))
print('-----------------------------')
print("BOTH ARE SERISE DATA TYPE")

Serise is a One Dimentional
-----------------------------
TYPE SERISE OF LIST DATA <class 'pandas.Series'>
TYPE SERISE OF DICTONARY DATA  <class 'pandas.Series'>
-----------------------------
BOTH ARE SERISE DATA TYPE

DATAFRAME

In [219]:
a ={
    'Emp_id' : [1,2,3,4,5],
    'Name' : ['sam','Mohit','Raj','Rahuel','Ankiet'],
    "Department" : ['it','sales','it','it','sales'],
    "Salary" : [20000,25000,30000,31000,26000]
}
print(a)

{'Emp_id': [1, 2, 3, 4, 5], 'Name': ['sam', 'Mohit', 'Raj', 'Rahuel', 'Ankiet'], 'Department': ['it', 'sales', 'it', 'it', 'sales'], 'Salary': [20000, 25000, 30000, 31000, 26000]}

In [220]:
df2 = pd.DataFrame(a)
df2

   Emp_id    Name Department  Salary
0       1     sam         it   20000
1       2   Mohit      sales   25000
2       3     Raj         it   30000
3       4  Rahuel         it   31000
4       5  Ankiet      sales   26000

In [221]:
df2

   Emp_id    Name Department  Salary
0       1     sam         it   20000
1       2   Mohit      sales   25000
2       3     Raj         it   30000
3       4  Rahuel         it   31000
4       5  Ankiet      sales   26000

Export Data Into Csv

In [222]:
# df2.to_csv("File_Path.csv")

Export Data Into Excel

In [223]:
# df.to_excel("File_Path.csv")

Import Data

In [224]:
# to import the data

In [225]:
df = pd.read_csv("Emp_data.csv")

In [226]:
df

   Unnamed: 0  Emp_id    Name Department  Salary
0           0       1     sam         it   20000
1           1       2   Mohit      sales   25000
2           2       3     Raj         it   30000
3           3       4  Rahuel         it   31000
4           4       5  Ankiet      sales   26000

In [227]:
exl = pd.read_excel("Student_Data2.xlsx")

In [228]:
exl

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000
4           4           5   Ankiet                7      126000
5           5           6      Dev                8     1220000
6           6           7    Sunil                9      125000
7           7           8      Ram               10      130000
8           8           9     Laxy               10      131000
9           9          10    Rahul               12      126000

head() --> By Default 5 Rows

In [229]:
exl.head()

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000
4           4           5   Ankiet                7      126000

tail() --> By Default 5 Last Rows

In [230]:
exl.tail()

   Unnamed: 0  Student_id   Name  Course_Duration  Total_Fess
5           5           6    Dev                8     1220000
6           6           7  Sunil                9      125000
7           7           8    Ram               10      130000
8           8           9   Laxy               10      131000
9           9          10  Rahul               12      126000

describe() --> Statically View Of the data

In [231]:
exl.describe()

       Unnamed: 0  Student_id  Course_Duration    Total_Fess
count    10.00000    10.00000         10.00000  1.000000e+01
mean      4.50000     5.50000          7.40000  2.644000e+05
std       3.02765     3.02765          2.91357  3.409872e+05
min       0.00000     1.00000          3.00000  1.250000e+05
25%       2.25000     3.25000          5.25000  1.260000e+05
50%       4.50000     5.50000          7.50000  1.305000e+05
75%       6.75000     7.75000          9.75000  2.052500e+05
max       9.00000    10.00000         12.00000  1.220000e+06

info() -->  it will return's the overall details of the data (Data Type Information)

In [232]:
exl.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       10 non-null     int64
 1   Student_id       10 non-null     int64
 2   Name             10 non-null     str
 3   Course_Duration  10 non-null     int64
 4   Total_Fess       10 non-null     int64
dtypes: int64(4), str(1)
memory usage: 532.0 bytes

In [233]:
exl

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000
4           4           5   Ankiet                7      126000
5           5           6      Dev                8     1220000
6           6           7    Sunil                9      125000
7           7           8      Ram               10      130000
8           8           9     Laxy               10      131000
9           9          10    Rahul               12      126000

loc[] --> label-based data selection method

*Iska use DataFrame se rows aur columns ko unke naam (labels) se select karne ke liye kiya jata hai

*na ki unki position (integer index) se

last index include hoti hai

loc[row_range , column_name]

In [234]:
exl.loc[0]

Unnamed: 0              0
Student_id              1
Name                Ankit
Course_Duration         3
Total_Fess         300000
Name: 0, dtype: object

In [235]:
exl.loc[0:3]

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000

In [236]:
exl.loc[6,'Name']

'Sunil'

In [237]:
print(exl.loc[0,['Student_id','Name']])
print('----------------------------')
print(exl.loc[1,['Student_id','Name']])

Student_id        1
Name          Ankit
Name: 0, dtype: object
----------------------------
Student_id       2
Name          Aman
Name: 1, dtype: object

iloc[] --> Integer-based Location

*eh ek powerful indexer hai jo DataFrame mein data select karne ke liye row aur column ke numerical positions (0 se shuru hone wale index) ka use karta hai

*na ki unke labels ka

last index exlude hoti hai

In [238]:
exl.iloc[0:3]

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000

In [239]:
exl

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000
4           4           5   Ankiet                7      126000
5           5           6      Dev                8     1220000
6           6           7    Sunil                9      125000
7           7           8      Ram               10      130000
8           8           9     Laxy               10      131000
9           9          10    Rahul               12      126000

Formula like this ---> iloc[row_index , column_index]

In [240]:
exl.iloc[6,2]

'Sunil'

In [241]:
exl

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000
4           4           5   Ankiet                7      126000
5           5           6      Dev                8     1220000
6           6           7    Sunil                9      125000
7           7           8      Ram               10      130000
8           8           9     Laxy               10      131000
9           9          10    Rahul               12      126000

In [242]:
exl.iloc[0,3]

np.int64(3)

In [243]:
b =df.empty ##it returns true if there any missing data in dataframe otherwise returns False
b

False

Check Missing Values

In [244]:
exl.isnull().sum()

Unnamed: 0         0
Student_id         0
Name               0
Course_Duration    0
Total_Fess         0
dtype: int64

For Remove Missing Row

In [245]:
exl.dropna() # For Remove Missing Row

   Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000
4           4           5   Ankiet                7      126000
5           5           6      Dev                8     1220000
6           6           7    Sunil                9      125000
7           7           8      Ram               10      130000
8           8           9     Laxy               10      131000
9           9          10    Rahul               12      126000

ndim --> Number of axis it is 2 (bcz DataFrame)

In [246]:
exl.ndim

2

shape --> (n(rows),n(columns))

In [247]:
exl.shape

(10, 5)

size --> row*coumns

In [248]:
exl.size

50

values --> # Get A NumPy Arrary For DataFrame

In [249]:
exl.values

array([[0, 1, 'Ankit', 3, 300000],
       [1, 2, 'Aman', 4, 125000],
       [2, 3, 'KaluRam', 5, 230000],
       [3, 4, 'Chetan', 6, 131000],
       [4, 5, 'Ankiet', 7, 126000],
       [5, 6, 'Dev', 8, 1220000],
       [6, 7, 'Sunil', 9, 125000],
       [7, 8, 'Ram', 10, 130000],
       [8, 9, 'Laxy', 10, 131000],
       [9, 10, 'Rahul', 12, 126000]], dtype=object)

In [250]:
a = exl.copy
a

<bound method NDFrame.copy of    Unnamed: 0  Student_id     Name  Course_Duration  Total_Fess
0           0           1    Ankit                3      300000
1           1           2     Aman                4      125000
2           2           3  KaluRam                5      230000
3           3           4   Chetan                6      131000
4           4           5   Ankiet                7      126000
5           5           6      Dev                8     1220000
6           6           7    Sunil                9      125000
7           7           8      Ram               10      130000
8           8           9     Laxy               10      131000
9           9          10    Rahul               12      126000>

sort_values() --> Values ko acending or desending order me set krta hai

In [251]:
df = pd.read_csv("placement.csv")
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [252]:
df = df.copy
df

<bound method NDFrame.copy of     cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]>

In [253]:
p = df().sort_values(by = 'resume_score')
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

# Cateogryical to Numerical

In [254]:
df = pd.read_csv("tips.csv")

In [255]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [256]:
df['sex'] = df['sex'].map({"Female":0,"Male":1})
df['smoker'] = df['smoker'].map({"Yes":0,"No":1})
df['day'] = df['day'].map({'Sat':1,'Sun':2,'Thur':3,'Fri':4})
df['time'] = df['time'].map({"Dinner":0,"Lunch":1})

In [257]:
df

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       1    2     0     2
1         10.34  1.66    1       1    2     0     3
2         21.01  3.50    1       1    2     0     3
3         23.68  3.31    1       1    2     0     2
4         24.59  3.61    0       1    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       1    1     0     3
240       27.18  2.00    0       0    1     0     2
241       22.67  2.00    1       0    1     0     2
242       17.82  1.75    1       1    1     0     2
243       18.78  3.00    0       1    3     0     2

[244 rows x 7 columns]

astype() #Type Conversion

In [258]:
df['total_bill'] = df['total_bill'].astype(int)

In [259]:
df

     total_bill   tip  sex  smoker  day  time  size
0            16  1.01    0       1    2     0     2
1            10  1.66    1       1    2     0     3
2            21  3.50    1       1    2     0     3
3            23  3.31    1       1    2     0     2
4            24  3.61    0       1    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239          29  5.92    1       1    1     0     3
240          27  2.00    0       0    1     0     2
241          22  2.00    1       0    1     0     2
242          17  1.75    1       1    1     0     2
243          18  3.00    0       1    3     0     2

[244 rows x 7 columns]

.add() --> TO incerement

In [260]:
df

     total_bill   tip  sex  smoker  day  time  size
0            16  1.01    0       1    2     0     2
1            10  1.66    1       1    2     0     3
2            21  3.50    1       1    2     0     3
3            23  3.31    1       1    2     0     2
4            24  3.61    0       1    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239          29  5.92    1       1    1     0     3
240          27  2.00    0       0    1     0     2
241          22  2.00    1       0    1     0     2
242          17  1.75    1       1    1     0     2
243          18  3.00    0       1    3     0     2

[244 rows x 7 columns]

In [261]:
p = df['total_bill'].add(4)

In [262]:
p

0      20
1      14
2      25
3      27
4      28
       ..
239    33
240    31
241    26
242    21
243    22
Name: total_bill, Length: 244, dtype: int64

In [264]:
df.count()

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

In [265]:
df.min()

total_bill    3.0
tip           1.0
sex           0.0
smoker        0.0
day           1.0
time          0.0
size          1.0
dtype: float64

In [266]:
df.max()

total_bill    50.0
tip           10.0
sex            1.0
smoker         1.0
day            4.0
time           1.0
size           6.0
dtype: float64

In [268]:
df.median()

total_bill    17.0
tip            2.9
sex            1.0
smoker         1.0
day            2.0
time           0.0
size           2.0
dtype: float64

filter() --> to filter Columns

In [270]:
df.filter(items = ['total_bill','tip'])

     total_bill   tip
0            16  1.01
1            10  1.66
2            21  3.50
3            23  3.31
4            24  3.61
..          ...   ...
239          29  5.92
240          27  2.00
241          22  2.00
242          17  1.75
243          18  3.00

[244 rows x 2 columns]

In [271]:
# Second Method to filter the columns

In [272]:
df[['total_bill','tip']]

     total_bill   tip
0            16  1.01
1            10  1.66
2            21  3.50
3            23  3.31
4            24  3.61
..          ...   ...
239          29  5.92
240          27  2.00
241          22  2.00
242          17  1.75
243          18  3.00

[244 rows x 2 columns]

Row Wise Filter TO Use axis = 0/1

o = row 
1 = columns

In [273]:
s =df.filter(items=[5,6],axis=0) #Row Wise Operation 
s

   total_bill   tip  sex  smoker  day  time  size
5          25  4.71    1       1    2     0     4
6           8  2.00    1       1    2     0     2

dataframe.rename(columns = {'col1_name':'Updated_name'})

In [276]:
df.rename(columns={'total_bill':"Total_Bill"})

     Total_Bill   tip  sex  smoker  day  time  size
0            16  1.01    0       1    2     0     2
1            10  1.66    1       1    2     0     3
2            21  3.50    1       1    2     0     3
3            23  3.31    1       1    2     0     2
4            24  3.61    0       1    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239          29  5.92    1       1    1     0     3
240          27  2.00    0       0    1     0     2
241          22  2.00    1       0    1     0     2
242          17  1.75    1       1    1     0     2
243          18  3.00    0       1    3     0     2

[244 rows x 7 columns]

In [278]:
df['half'] = df['total_bill'].where(df['total_bill'] >7 , other=0)
df.head(10)
# where are used to check the condition is true or not and other fill the 0 if condition is false

   total_bill   tip  sex  smoker  day  time  size  half
0          16  1.01    0       1    2     0     2    16
1          10  1.66    1       1    2     0     3    10
2          21  3.50    1       1    2     0     3    21
3          23  3.31    1       1    2     0     2    23
4          24  3.61    0       1    2     0     4    24
5          25  4.71    1       1    2     0     4    25
6           8  2.00    1       1    2     0     2     8
7          26  3.12    1       1    2     0     4    26
8          15  1.96    1       1    2     0     2    15
9          14  3.23    1       1    2     0     2    14