In [1]:
print("Pandas Pratice !")

Pandas Pratice !

In [2]:
import pandas as pd

In [3]:
data = {
     'a':1,
     'b':2,
     'c':3
}

In [4]:
data

{'a': 1, 'b': 2, 'c': 3}

In [6]:
data.keys()

dict_keys(['a', 'b', 'c'])

In [7]:
data.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [8]:
data.values()

dict_values([1, 2, 3])

In [9]:
s = {v:k for k,v in data.items()}

In [10]:
s

{1: 'a', 2: 'b', 3: 'c'}

In [14]:
# df = pd.DataFrame(s)

In [17]:
data = {
    "name": ['Dev','aman','babu'],
    "age" : [19,17,20]
    
}

In [18]:
df = pd.DataFrame(data)

In [19]:
df.head()

   name  age
0   Dev   19
1  aman   17
2  babu   20

In [20]:
df.tail()

   name  age
0   Dev   19
1  aman   17
2  babu   20

In [21]:
df.shape

(3, 2)

In [22]:
df.columns

Index(['name', 'age'], dtype='str')

In [23]:
df.size

6

In [24]:
df.sample

<bound method NDFrame.sample of    name  age
0   Dev   19
1  aman   17
2  babu   20>

In [25]:
df.all

<bound method DataFrame.all of    name  age
0   Dev   19
1  aman   17
2  babu   20>

In [26]:
df.any

<bound method DataFrame.any of    name  age
0   Dev   19
1  aman   17
2  babu   20>

In [29]:
# df.mean()

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [35]:
df.describe()

             age
count   3.000000
mean   18.666667
std     1.527525
min    17.000000
25%    18.000000
50%    19.000000
75%    19.500000
max    20.000000